### ISSUE TITLE
是否可以选择原版已经训练过的emb再使用这个apt进行二次训练？

### ISSUE THREAD

**Issue by gitmithy** [AiMiDi/stable-diffusion-webui-advance-prompt-tuning#1]
rt

**Comment by gitmithy** [comment]
能选择在原版已经训练过的emb，再进行二次使用这个进行训练么，会产生什么冲突吗？还是重新新建emb从0开始训练比较好？
因为原版我有个效果不错的emb，想拿这个emb继续调优

**Comment by AiMiDi** [comment]
Theoretically it is compatible, because they build and check the Checkpoint in the same way, but the training method has been adjusted to open more parameters out, keeping the original parameters is the same as the original version.
There are still bugs that lead to the inability to train, still debugging, welcome interested developers to join.

理论上是兼容的，因为他们建立和检查Checkpoint的方式都一样，但是训练方式有调整，开了更多参数出来，保持原参数是和原版一样的。
目前还有导致无法训练的bug，还在调试，欢迎感兴趣的开发者加入。
